#!/usr/bin/env python3
"""Import the WooCommerce README downloaded by the sync workflow."""
import argparse
from pathlib import Path
import re
from urllib.parse import urljoin, urlsplit

SOURCE = 'https://github.com/bluepayment-plugin/autopay-payments/blob/main/README.md'
RAW_BASE = 'https://raw.githubusercontent.com/bluepayment-plugin/autopay-payments/main/'
BLOB_BASE = 'https://github.com/bluepayment-plugin/autopay-payments/blob/main/'
DESTINATION = Path(__file__).resolve().parents[1] / 'wtyczki-e-commerce/woocommerce.md'


def absolute_url(url, image=False):
    if not url or url.startswith(('#', '//')) or urlsplit(url).scheme:
        return url
    return urljoin(RAW_BASE if image else BLOB_BASE, url.lstrip('/'))


def rewrite_links(text):
    # Preserve fenced and inline code verbatim. Rewrite Markdown inline links,
    # reference definitions, and quoted HTML image/link attributes in prose.
    parts = re.split(r'(^[ \t]*```[^\n]*\n.*?^[ \t]*```[^\n]*$|^[ \t]*~~~[^\n]*\n.*?^[ \t]*~~~[^\n]*$|`+[^`\n]*`+)', text, flags=re.M | re.S)
    for i in range(0, len(parts), 2):
        part = parts[i]
        part = re.sub(
            r'(!?\[[^\]\n]*\]\()(<[^>\n]+>|(?:[^\s()]|\([^()]*\))+)',
            lambda m: m[1] + ('<' + absolute_url(m[2][1:-1], m[1].startswith('!')) + '>' if m[2].startswith('<') else absolute_url(m[2], m[1].startswith('!'))),
            part,
        )
        # Raw URLs work for both linked documents and images in reference syntax.
        part = re.sub(r'^( {0,3}\[[^\]\n]+\]:\s*)(<?)([^\s>]+)(>?)',
                      lambda m: m[1] + m[2] + absolute_url(m[3], True) + m[4], part, flags=re.M)
        part = re.sub(r'\b(src|href)=("|\x27)(.*?)\2',
                      lambda m: m[1] + '=' + m[2] + absolute_url(m[3], m[1] == 'src') + m[2], part, flags=re.S)
        parts[i] = part
    return ''.join(parts)


def render(source):
    if not source.strip() or not re.search(r'^#\s+.+', source, re.M):
        raise ValueError('Downloaded README must be non-empty Markdown with an H1; existing page was not changed.')
    return ('<!-- Generated by scripts/sync_woocommerce_readme.py.\n'
            f'Source: {SOURCE}\n'
            'Edit the upstream README; local changes are overwritten by the daily sync. -->\n\n'
            + rewrite_links(source).rstrip() + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path, help='Downloaded UTF-8 README')
    args = parser.parse_args()
    content = render(args.source.read_text(encoding='utf-8'))
    if DESTINATION.exists() and DESTINATION.read_text(encoding='utf-8') == content:
        print('WooCommerce documentation is already up to date.')
        return
    temporary = DESTINATION.with_suffix('.md.tmp')
    temporary.write_text(content, encoding='utf-8')
    temporary.replace(DESTINATION)
    print(f'Updated {DESTINATION.relative_to(DESTINATION.parents[1])}')


if __name__ == '__main__':
    main()
